# Generated by Django 5.0.6 on 2024-06-13 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0002_alter_persona_apellidos_alter_persona_edad_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persona',
            old_name='nombres',
            new_name='nombre',
        ),
    ]
